{% set name = "emmet-builders" %}
{% set version = "0.87.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 161b20665d82da20f2592c7345dfb6962555d999655a90e9817eb25bb786f5bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools
    - pip
  run:
    - pymatgen-io-validation >=0.1.1
    - python >={{ python_min }}
    - emmet-core >=0.86.1
    - maggma >=0.57.6
    - matminer >=0.10.0

test:
  imports:
    - emmet.builders
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/emmet
  summary: Builders for the Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
